### ISSUE TITLE
Viewer and hour count 

### ISSUE THREAD

**Issue by RyanIsSwag** [Turqmelon/PBat-Live#4] opened 2016-05-16 23:57 UTC
It seems the video has covered up the text. I have no idea if it's just a problem on my end. 
![web bug](https://cloud.githubusercontent.com/assets/19398165/15307366/32a79f0e-1bca-11e6-85a2-8cd32db457a3.png)

**Comment by Turqmelon** [comment] 2016-05-17 00:26
This is a duplicate of #3

**Closed by Turqmelon** 2016-05-17 00:26 UTC
